---
title: "Visualização de dados em ggplot"
subtitle: ""
author: "Guilherme D. Garcia e Ronaldo Lima Jr."
institute: "• Université Laval e UnB•"
date: ""
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts", "myStyles.css"]
    lib_dir: libs
    includes:
      after_body: "myStyles.css"
    nature:
      highlightStyle: github
      ratio: '16:9'
      center: true
      slideNumberFormat: "%current% de %total%"
      highlightLines: true
      countIncrementalSlides: false
    seal: false
---

```{r setup, include=FALSE}
library(fontawesome)
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

class: title-slide, inverse, center, middle

# Workshop
## Visualização de dados com ggplot
<a href = "https://gdgarcia.ca" style="color: #FEC20B">Guilherme D. Garcia</a> | Université Laval • Centre for Research on Brain, Language & Music (CRBLM) 

<a href = "http://ronaldolimajr.github.io" style="color: #FEC20B">Ronaldo Lima Jr.</a> | Universidade de Brasília • CNPq


<!-- #### Université Laval • Centre for Research on Brain, Language & Music (CRBLM) -->
<!-- #### Universidade de Brasília • CNPq -->

---

```{r xaringanExtra, echo=FALSE}
# xaringanExtra::use_tile_view()
xaringanExtra::use_scribble()
xaringanExtra::use_clipboard(button_text = "Clique para copiar", success_text = "Copiado!")
# xaringanExtra::use_search(show_icon = TRUE)
xaringanExtra::use_progress_bar(location = "bottom", color = "darkred")
options(htmltools.dir.version = FALSE)
xaringanExtra::use_editable()
xaringanExtra::use_panelset()
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = FALSE  #<<
)

```

## Apresentação

- ...

---

## Questionário

- MS Forms

---

## Tipos de gráficos


---

## Boas práticas


---

## Dos and don'ts


---

## Introdução ao `ggplot2`


---

## Visualização descritiva

---

## Prática

